[project]
name = "sdvosb-federal-analytics"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "judsonlyates", email = "judsonyates220@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
]

[project.scripts]
sdvosb-federal-analytics = "sdvosb_federal_analytics:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
